#! /bin/bash

# The MIT License (MIT)
# Copyright (c) 2022 Emeer Adhamian (github.com/kode-trek)
# https://github.com/kode-trek/who/blob/main/LICENSE
# https://github.com/kode-trek/archive/blob/main/LICENSE

sudo apt-get update
sudo apt-get install -y php
sudo apt-get install -y apache2
sudo apt-get install -y libapache2-mod-php
#sudo apt-get install mysql-server

sudo chown -R www-data:www-data /var/www/html
sudo gzip /var/www/html/index.html
