#! /bin/bash

sudo rm -r /var/www/html/who/
sudo mkdir /var/www/html/who/
sudo cp lib/* /var/www/html/who/
sudo chown -R www-data:www-data /var/www/html/who

sudo gzip /etc/php/7.4/apache2/php.ini
sudo cp lib/conf/php-ORIGINAL.ini /etc/php/7.4/apache2/php.ini
sudo /etc/init.d/apache2 restart
